##################### Rails ##################################

# By default Rails is switched off so this can be used by non-Rails apps,
# this can be enabled in a local .rubocop.yml file
Rails:
  Enabled: false

ActionFilter:
  Description: 'Enforces consistent use of action filter methods.'
  Enabled: false

Delegate:
  Description: 'Prefer delegate method for delegations.'
  Enabled: false

HasAndBelongsToMany:
  Description: 'Prefer has_many :through to has_and_belongs_to_many.'
  Enabled: false

Output:
  Description: 'Checks for calls to puts, print, etc.'
  Enabled: false

ReadWriteAttribute:
  Description: 'Checks for read_attribute(:attr) and write_attribute(:attr, val).'
  Enabled: false

ScopeArgs:
  Description: 'Checks the arguments of ActiveRecord scopes.'
  Enabled: false

Validation:
  Description: 'Use sexy validations.'
  Enabled: false

SkipsModelValidations:
  Description: 'Avoid methods that skip model validations.'
  Enabled: false
